project_id = "pluralith"
bucket_name = "pluralith-cli-releases"
bucket_location = "us-central1"
cloud_build_trigger_name = "pluralith-cli-build"
cloud_build_trigger_description = "Build and publish latest version of Pluralith CLI for supported platforms"
repo_owner = "Pluralith"
repo_name = "pluralith-cli"
repo_branch = "main"